FROM oven/bun:1

ARG DATABASE_URL

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web


RUN bun install

RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build 

EXPOSE 3000

# Start the frontend application
CMD ["bun","run", "start:frontend"]